### ISSUE TITLE
Installation fails due [update host to install new os] task 

### ISSUE THREAD

**Issue by asyedham** [redhat-performance/jetpack#100]
When deploying OSP13 if the machines have RHEL 8 installed it fails to update host to install new os  with this error
TASK [update host to install new os] **********************************************************************************
fatal: [localhost -> hwstore.redhat.com]: FAILED! => {"changed": false, "module_stderr": "Shared connecti
on to hwstore.redhat.com closed.\r\n", "module_stdout": "/bin/sh: /usr/libexec/platform-python: No such f
ile or directory\r\n", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee s
tdout/stderr for the exact error", "rc": 127}                                                                         
                                                                                                                      
PLAY RECAP ************************************************************************************************************
localhost                  : ok=23   changed=5    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by smalleni** [comment]
@asyedham hammer_host should not be hwstore.redhat.com. Please check the jetpack vars doc shared with you.

**Comment by smalleni** [comment]
Not a valid issue.
