### ISSUE TITLE
vxlan not set for osp13

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#133]
vxlan is set to true [1] from the contents of files added in below extra.yml. But this fistbot.yml is not having vxlan string, so vxlan is never set. 

[root@f19-h10-000-r620 jetpack]# cat ~/infrared/plugins/tripleo-overcloud/vars/overcloud/templates/extra.yml
---
tripleo_heat_templates:
    - /home/stack/firstboot.yaml

I am getting this below error
https://gist.github.com/venkataanil/396180439ca2044610a16b4f1b320111

[1] https://github.com/smalleni/jetpack/commit/0426a12cefbbf73d7e567b58d4b9c09450f853cc#diff-d82d1754e42f3800a25e9cd02a0cb3a3R79

**Comment by smalleni** [comment]
@venkataanil your error seems to be due to not having the search filter. Otherwise line 115 in overcloud.yml should correctly set the backend.
