### ISSUE TITLE
Python Requirement for Using Jetpack

### ISSUE THREAD

**Issue by xuhang57** [redhat-performance/jetpack#134]
In OSP 13, it has python2 as the default python environment. And in the README, it notes that Jetpack requires a Python 3.6+ environment. However, as far as I know, jetpack supports to deploy OSP 13 on the scale lab machines. Maybe a quick update or note on the README? 

Thanks!

**Comment by smalleni** [comment]
jetpack is run from outside the cloud/undercloud so this is not an issue :)
