### ISSUE TITLE
OSP16 should use RHEL8.1

### ISSUE THREAD

**Issue by zulcss** [redhat-performance/jetpack#151]
The hammer should be RHEL 8.1 if the user is installing OSP16.

**Comment by kambiz-aghaiepour** [comment]
I forgot about the fact that you guys were using hammer and relying on the OS names.  I recently added a way for being specific about the version of RHEL8 by setting the host to either "RHEL 8.0" or "RHEL 8.1" (formerly "RHEL8" if I'm not mistaken).  You can also force a host marked as "RHEL 8.0" to upgrade to 8.1 using foreman host parameter of "rhel81" and setting it to "True" (string not boolean)

**Comment by venkataanil** [comment]
Thanks Kambiz.
Commit f8af08e90756aba89b8c6202cbcba1b1cf3939af fixed this issue.
