### ISSUE TITLE
[RFE] [OSP16] Environment variable with option for OVN with DVR-HA

### ISSUE THREAD

**Issue by pradiptapks** [redhat-performance/jetpack#166]
Currently, Jetpack deploy osp16 with default ml2-ovn with ovn ha service template, where the controllers are act a gateway chassis.

`/usr/share/openstack-tripleo-heat-templates/environments/services/neutron-ovn-ha.yaml`

For DVR based deployment, Jetpack environment "jetpack/group_vars/all.yml" needs enhancement with ovn_dvr option which can deploy the overcloud with the ovn-dvr-ha service template, if the compute have dedicated external NIC.
`/usr/share/openstack-tripleo-heat-templates/environments/services/neutron-ovn-dvr-ha.yaml`

**Comment by smalleni** [comment]
@pradiptapks Thanks for bringing this up, but can we not use the extra_templates option in group_vars/all.yml to pass the DVR template?

**Comment by smalleni** [comment]
https://github.com/redhat-performance/jetpack/pull/167 should address this
