### ISSUE TITLE
pxe boot for ALIAS dell machines failing as urllib3 missing for badfish

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#182]
TASK [set undercloud to PXE boot off Foreman (Dell)] ************************************************************************************************************************
task path: /root/jetpack/setup_undercloud.yml:113
FAILED - RETRYING: set undercloud to PXE boot off Foreman (Dell) (5 retries left).
FAILED - RETRYING: set undercloud to PXE boot off Foreman (Dell) (4 retries left).
FAILED - RETRYING: set undercloud to PXE boot off Foreman (Dell) (3 retries left).
FAILED - RETRYING: set undercloud to PXE boot off Foreman (Dell) (2 retries left).
FAILED - RETRYING: set undercloud to PXE boot off Foreman (Dell) (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 5, "changed": true, "cmd": "source /root/badfish/.venv/bin/activate\npython3 badfish.py -H mgmt-e25-h21-740xd.alias.bos.scalelab.
redhat.com -u quads -p 504492 -i config/idrac_interfaces.yml --boot-to-type foreman --pxe\n", "delta": "0:00:00.030093", "end": "2020-04-27 18:40:07.533482", "msg": "non-zer
o return code", "rc": 1, "start": "2020-04-27 18:40:07.503389", "stderr": "Traceback (most recent call last):\n  File \"badfish.py\", line 2, in <module>\n    from urllib3.e
xceptions import MaxRetryError\nModuleNotFoundError: No module named 'urllib3'", "stderr_lines": ["Traceback (most recent call last):", "  File \"badfish.py\", line 2, in <m
odule>", "    from urllib3.exceptions import MaxRetryError", "ModuleNotFoundError: No module named 'urllib3'"], "stdout": "", "stdout_lines": []}

**Comment by grafuls** [comment]
This has been resolved in the latest badfish under development branch. You might also want to look into running badfish from it's container image.
