### ISSUE TITLE
Jetpack ci job for osp13 failing

### ISSUE THREAD

**Issue by asyedham** [redhat-performance/jetpack#192]
TASK [fail when compute count is less than 1] **********************************
task path: /home/jetpack/workspace/jetpack-ci-osp13/overcloud.yml:104
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "msg": "Failing as compute count is less than 1"
}
	to retry, use: --limit @/home/jetpack/workspace/jetpack-ci-osp13/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=67   changed=19   unreachable=0    failed=1   
undercloud                 : ok=25   changed=12   unreachable=0    failed=0   

Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Adding one-line test results to commit status...
Setting status of d5d67e2fa74fd25ba94929a54eb951e2cb0a71bb to SUCCESS with url http://tesla.rdu.openstack.engineering.redhat.com:8080/job/jetpack-ci-osp13/57/ and message: 'Deployed
 No test results found.'
Using context: osp 13
Finished: SUCCESS

**Comment by masco** [comment]
https://github.com/redhat-performance/jetpack/pull/228

**Comment by masco** [comment]
The PR is merged, and the Job is up and running.
