### ISSUE TITLE
Ansible task failing when changing node state from ""clean wait" to "available" after introspection

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#200]
Some times below jetpack task is failing in my setup. This task will check if the node is not in available state for the successfully introspected nodes and then change them to available state. Looks like the machines are moving to intermediate "clean wait" state after the introspection and then to "available" state.

This task is failing as we are trying to change state from ""clean wait" to "available".

When I manually logged into undercloud after some time, I could see all nodes in available state.

TASK [set provision state of all nodes to available] ************************************************************************************************************************
task path: /root/jetpack/tasks/delete_introspection_failed_nodes.yml:47
failed: [undercloud] (item=3e9dbe96-380c-4954-b99a-a8c22ab74ec3) => {"ansible_loop_var": "item", "changed": false, "cmd": "source ~/stackrc;\nexport PROV_STATE=$(openstack b
aremetal node show 3e9dbe96-380c-4954-b99a-a8c22ab74ec3 -c provision_state -f value);\nif [[ $PROV_STATE != *\"available\"* ]]; then\n    openstack baremetal node provide 3e
9dbe96-380c-4954-b99a-a8c22ab74ec3;\nfi\n", "delta": "0:00:03.179086", "end": "2020-05-20 10:19:58.360728", "item": "3e9dbe96-380c-4954-b99a-a8c22ab74ec3", "msg": "non-zero 
return code", "rc": 1, "start": "2020-05-20 10:19:55.181642", "stderr": "The requested action \"provide\" can not be performed on node \"3e9dbe96-380c-4954-b99a-a8c22ab74ec3
\" while it is in state \"clean wait\". (HTTP 400)", "stderr_lines": ["The requested action \"provide\" can not be performed on node \"3e9dbe96-380c-4954-b99a-a8c22ab74ec3\"
 while it is in state \"clean wait\". (HTTP 400)"], "stdout": "", "stdout_lines": []}
failed: [undercloud] (item=4f4421e5-4f26-40b5-bd56-ebc06e1853fb) => {"ansible_loop_var": "item", "changed": false, "cmd": "source ~/stackrc;\nexport PROV_STATE=$(openstack b
aremetal node show 4f4421e5-4f26-40b5-bd56-ebc06e1853fb -c provision_state -f value);\nif [[ $PROV_STATE != *\"available\"* ]]; then\n    openstack baremetal node provide 4f
4421e5-4f26-40b5-bd56-ebc06e1853fb;\nfi\n", "delta": "0:00:03.275994", "end": "2020-05-20 10:20:01.946819", "item": "4f4421e5-4f26-40b5-bd56-ebc06e1853fb", "msg": "non-zero 
return code", "rc": 1, "start": "2020-05-20 10:19:58.670825", "stderr": "The requested action \"provide\" can not be performed on node \"4f4421e5-4f26-40b5-bd56-ebc06e1853fb
\" while it is in state \"clean wait\". (HTTP 400)", "stderr_lines": ["The requested action \"provide\" can not be performed on node \"4f4421e5-4f26-40b5-bd56-ebc06e1853fb\"
 while it is in state \"clean wait\". (HTTP 400)"], "stdout": "", "stdout_lines": []}
failed: [undercloud] (item=11aceb6e-6095-43cd-a949-343d66bc8022) => {"ansible_loop_var": "item", "changed": false, "cmd": "source ~/stackrc;\nexport PROV_STATE=$(openstack b
aremetal node show 11aceb6e-6095-43cd-a949-343d66bc8022 -c provision_state -f value);\nif [[ $PROV_STATE != *\"available\"* ]]; then\n    openstack baremetal node provide 11
aceb6e-6095-43cd-a949-343d66bc8022;\nfi\n", "delta": "0:00:03.102533", "end": "2020-05-20 10:20:05.370655", "item": "11aceb6e-6095-43cd-a949-343d66bc8022", "msg": "non-zero 
return code", "rc": 1, "start": "2020-05-20 10:20:02.268122", "stderr": "The requested action \"provide\" can not be performed on node \"11aceb6e-6095-43cd-a949-343d66bc8022
\" while it is in state \"clean wait\". (HTTP 400)", "stderr_lines": ["The requested action \"provide\" can not be performed on node \"11aceb6e-6095-43cd-a949-343d66bc8022\"
 while it is in state \"clean wait\". (HTTP 400)"], "stdout": "", "stdout_lines": []}
failed: [undercloud] (item=45bb5574-6150-4ea2-b86b-ef88d80563d9) => {"ansible_loop_var": "item", "changed": false, "cmd": "source ~/stackrc;\nexport PROV_STATE=$(openstack b
aremetal node show 45bb5574-6150-4ea2-b86b-ef88d80563d9 -c provision_state -f value);\nif [[ $PROV_STATE != *\"available\"* ]]; then\n    openstack baremetal node provide 45
bb5574-6150-4ea2-b86b-ef88d80563d9;\nfi\n", "delta": "0:00:03.127038", "end": "2020-05-20 10:20:08.819153", "item": "45bb5574-6150-4ea2-b86b-ef88d80563d9", "msg": "non-zero 
return code", "rc": 1, "start": "2020-05-20 10:20:05.692115", "stderr": "The requested action \"provide\" can not be performed on node \"45bb5574-6150-4ea2-b86b-ef88d80563d9
\" while it is in state \"clean wait\". (HTTP 400)", "stderr_lines": ["The requested action \"provide\" can not be performed on node \"45bb5574-6150-4ea2-b86b-ef88d80563d9\"
 while it is in state \"clean wait\". (HTTP 400)"], "stdout": "", "stdout_lines": []}
failed: [undercloud] (item=e9e72c1a-62fb-4679-9971-310f3c90cf0c) => {"ansible_loop_var": "item", "changed": false, "cmd": "source ~/stackrc;\nexport PROV_STATE=$(openstack b
aremetal node show e9e72c1a-62fb-4679-9971-310f3c90cf0c -c provision_state -f value);\nif [[ $PROV_STATE != *\"available\"* ]]; then\n    openstack baremetal node provide e9
e72c1a-62fb-4679-9971-310f3c90cf0c;\nfi\n", "delta": "0:00:03.074345", "end": "2020-05-20 10:20:12.218994", "item": "e9e72c1a-62fb-4679-9971-310f3c90cf0c", "msg": "non-zero 
return code", "rc": 1, "start": "2020-05-20 10:20:09.144649", "stderr": "The requested action \"provide\" can not be performed on node \"e9e72c1a-62fb-4679-9971-310f3c90cf0c
\" while it is in state \"clean wait\". (HTTP 400)", "stderr_lines": ["The requested action \"provide\" can not be performed on node \"e9e72c1a-62fb-4679-9971-310f3c90cf0c\"
 while it is in state \"clean wait\". (HTTP 400)"], "stdout": "", "stdout_lines": []}

**Comment by masco** [comment]
https://github.com/redhat-performance/jetpack/pull/203
https://github.com/redhat-performance/jetpack/pull/209

fixes are merged to the master
