### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by zulcss** [redhat-performance/jetpack#23]
TASK [show addresses] ***********************************************************************************************************************
failed: [e23-h15-740xd.alias.bos.scalelab.redhat.com] (item=p7p1) => {"ansible_loop_var": "item", "changed": false, "cmd": "set -o pipefail\nip -4 address show p7p1 | grep inet | awk '{ print $2}'\n", "delta": "0:00:00.007297", "end": "2019-09-22 18:17:58.573983", "item": "p7p1", "msg": "non-zero return code", "rc": 1, "start": "2019-09-22 18:17:58.566686", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
failed: [e23-h15-740xd.alias.bos.scalelab.redhat.com] (item=p7p2) => {"ansible_loop_var": "item", "changed": false, "cmd": "set -o pipefail\nip -4 address show p7p2 | grep inet | awk '{ print $2}'\n", "delta": "0:00:00.007392", "end": "2019-09-22 18:18:00.568693", "item": "p7p2", "msg": "non-zero return code", "rc": 1, "start": "2019-09-22 18:18:00.561301", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
failed: [e23-h15-740xd.alias.bos.scalelab.redhat.com] (item=em1) => {"ansible_loop_var": "item", "changed": false, "cmd": "set -o pipefail\nip -4 address show em1 | grep inet | awk '{ print $2}'\n", "delta": "0:00:00.007203", "end": "2019-09-22 18:18:02.614841", "item": "em1", "msg": "non-zero return code", "rc": 1, "start": "2019-09-22 18:18:02.607638", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
failed: [e23-h15-740xd.alias.bos.scalelab.redhat.com] (item=em2) => {"ansible_loop_var": "item", "changed": false, "cmd": "set -o pipefail\nip -4 address show em2 | grep inet | awk '{ print $2}'\n", "delta": "0:00:00.007350", "end": "2019-09-22 18:18:04.541569", "item": "em2", "msg": "non-zero return code", "rc": 1, "start": "2019-09-22 18:18:04.534219", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
ok: [e23-h15-740xd.alias.bos.scalelab.redhat.com] => (item=em3)

PLAY RECAP **********************************************************************************************************************************
e23-h15-740xd.alias.bos.scalelab.redhat.com : ok=16   changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=1   
localhost                  : ok=29   changed=5    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0

**Comment by smalleni** [comment]
This is no longer an issue, please reopen if you run into it again.
