### ISSUE TITLE
[RFE] Support scale up operations

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/jetpack#242]
JetSki right now by default always deletes existing overcloud before redeploying on the same hardware. It would be nice to have JetSki support scale up operations. It shouldn;t be too hard

1. Check if infrared natively supports scale up operation on cli and use that
2. Even otherwise, a regular openstack overcloud deploy as triggered by infrared with a new worker count should only result in scale up given: a. We don't delete existing overcloud explicitly as we currently do, and don't reimport/reintrospect same nodes and directly go the overcloud deploy part. after importing/inspecting new nodes.

**Comment by venkataanil** [comment]
Better not to use infrared and instead directly jetpack update the instackenv and run commands on undercloud for scale up activities.
