### ISSUE TITLE
Bump max concurrent builds to speed up overcloud deployment

### ISSUE THREAD

**Issue by akrzos** [redhat-performance/jetpack#272]
Looks like [infrared](https://github.com/redhat-openstack/infrared/blob/master/plugins/tripleo-overcloud/deploy.yml#L62) specifically reduced the number of nodes that can concurrently be built to 5, when we could speed this process up for consumers of the scale lab with larger undercloud machines.  We should set this back to 10 or work with infrared to allow us to have an override for the scale lab.

**Comment by smalleni** [comment]
@akrzos looks like infrared does this only for OSP version <  10?

**Comment by akrzos** [comment]
Hmm, I checked my logs and found this task, so it looks like I found the incorrect task:

```
# cat jetpack/logs/undercloud_install.log | grep "max_concurrent_builds" -i -A 3 
TASK [set max_concurrent_builds via hieradata] *********************************
task path: /root/.infrared/plugins/tripleo-undercloud/configure.yml:108
changed: [undercloud] => {"changed": true, "checksum": "2a5aad735800b652c712c57b6c387c65e15e6e3a", "dest": "/home/stack/hiera_override.yaml", "gid": 1000, "group": "stack", "md5sum": "7222df98f249589f821e21ed0130e2bd", "mode": "0664", "owner": "stack", "secontext": "unconfined_u:object_r:user_home_t:s0", "size": 47, "src": "/home/stack/.ansible/tmp/ansible-tmp-1603891282.279306-149304-276139875201192/source", "state": "file", "uid": 1000}
```
So it looks like this [line](https://github.com/redhat-openstack/infrared/blob/master/plugins/tripleo-undercloud/configure.yml#L108) is causing the change for us then
