### ISSUE TITLE
Inventory generation failed

### ISSUE THREAD

**Issue by zulcss** [redhat-performance/jetpack#30]
TASK [Add undercloud_host after setting python interpereter (RHEL 8)] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check ''interpreter' in ping_output.msg' failed. The error was: error while evaluating conditional ('interpreter' in ping_output.msg): Unable to look up a name or access an attribute in template string ({% if 'interpreter' in ping_output.msg %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'AnsibleUndefined' is not iterable\n\nThe error appears to be in '/home/chuck/work/jetpack/tasks/prepare_inventory.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Add undercloud_host after setting python interpereter (RHEL 8)\n  ^ here\n"}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************************

PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=16   changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by smalleni** [comment]
This should have been fixed by https://github.com/redhat-performance/jetpack/commit/c43755bd3479731226e709358e5e30c745885854
