### ISSUE TITLE
Setup is a bit vague

### ISSUE THREAD

**Issue by jtaleric** [redhat-performance/jetpack#31]
`Clone and setup infrared environment`

At which point do I need to stop the Infrared `setup` ? For example, is this all that is needed? https://infrared.readthedocs.io/en/latest/bootstrap.html#setup

**Comment by jtaleric** [comment]
Digging through `/home/jtaleric/Code/Work/jetpack/tasks/setup_infrared.yml` it would seem that there really isn't any setup needed

**Comment by smalleni** [comment]
Yeh readme needs updating I guess. Jetpack sets up everything.

**Comment by smalleni** [comment]
@jtaleric Actually I just had a look at README. It does not ask the user to follow those steps. It states that those are the internal tasks done by jetpack

"Below are the sequence of steps these playbooks run before deploying overcloud"

**Comment by jtaleric** [comment]
ah ha! yup, my eyes skipped that line `Below are the sequence of steps these playbooks run before deploying overcloud`
