### ISSUE TITLE
support scale lab fc640

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#350]
These are the new Dell devices in scale lab.
Some machines have 3 interfaces and some machines have 5 interfaces.
Need to test badfish commands and boot order in these machines.

**Comment by asyedham** [comment]
As discussed we will not be adding support for fc640 in Jetpack as basically some FC640 systems (the ones that have Mellanox cards) will have the device names eth2 and eth3 for the Intel interfaces, and the ens2f0 and ens2f1 names become associated with the Mellanox interfaces. Jetpack will not support same machines that have heterogeneous interfaces.

**Comment by venkataanil** [comment]
According to http://wiki.scalelab.redhat.com/faq/ hosts on racks "e23-h12, e23-h24, e23-h36" have 5 interfaces. So Jetpack can have composable roles based on the rack on which fc640 hosted.

While deploying OSP16.2 on fc640 (which has 3 interfaces) I faced below issues

1. fc640 interfaces not added in group_vars
TASK [set interfaces] *******************************************************************************************************************************************************
task path: /root/jetpack/prepare_nic_configs.yml:31
Wednesday 18 August 2021  18:38:19 +0000 (0:00:00.069)       0:05:37.147 ******
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'fc640'\n\nThe error appears to be in '/root/jetpack/prepare_nic_configs.yml': line 31, column 13, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n          - name: set interfaces\n            ^ here\n"}

2. Not sure why composable.yml playbook running though I have only one node type in my allocation. Got this error
TASK [setting profile for node type] ****************************************************************************************************************************************
task path: /root/jetpack/composable.yml:117
Wednesday 18 August 2021  20:02:57 +0000 (0:00:00.055)       1:16:39.305 ******
fatal: [undercloud]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}

3. overcloud deploy was failing
When we have 3 interfaces, ControlPlaneIp and ExternalIpSubnet will use same bridge i.e br-ctlplane. However Jetpack's post.yaml create vlan interface (ens2f0.300) instead of creating vlan300 on br-ctlplane in undercloud. So post.yaml has to be updated like below when we have 3 interfaces
sudo ovs-vsctl add-port br-ctlplane vlan300 tag=300 -- set interface vlan300 type=internal
sudo ip a a 172.18.0.1/16 dev vlan300
sudo ip l s vlan300 up
