### ISSUE TITLE
infrared overcloud deployment failing in all-in-one envrionment

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#399]
TASK [Copy deployment folder] ***********************************************************************************************************************************************
^[[1;30mtask path: /root/.infrared/plugins/tripleo-overcloud/build_templates.yml:75^[[0m
^[[0;31mfailed: [undercloud-0] (item={'root': '/root/.infrared/plugins/tripleo-overcloud/vars/deployment/files/virt', 'path': 'network/baremetal_deployment.yaml.j2', 'state': 'file', 'src': '/root/.infrared/plugins/tripleo-overcloud/vars/deployment/files/virt/network/baremetal_deployment.yaml.j2', 'uid': 0, 'gid': 0, 'owner': 'root', 'group': 'root', 'mode': '0644', 'size': 1974, 'mtime': 1629097757.5778325, 'ctime': 1629097808.4760115, 'seuser': 'unconfined_u', 'serole': 'object_r', 'setype': 'admin_home_t', 'selevel': 's0'}) => {"ansible_loop_var": "item", "changed": false, "item": {"ctime": 1629097808.4760115, "gid": 0, "group": "root", "mode": "0644", "mtime": 1629097757.5778325, "owner": "root", "path": "network/baremetal_deployment.yaml.j2", "root": "/root/.infrared/plugins/tripleo-overcloud/vars/deployment/files/virt", "selevel": "s0", "serole": "object_r", "setype": "admin_home_t", "seuser": "unconfined_u", "size": 1974, "src": "/root/.infrared/plugins/tripleo-overcloud/vars/deployment/files/virt/network/baremetal_deployment.yaml.j2", "state": "file", "uid": 0}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'backend'"}^[[0m

**Comment by venkataanil** [comment]
Passing " --storage-backend lvm" option helping deployment succeed  i.e

infrared tripleo-overcloud -vv --introspect no --tagging no --deploy yes --version 16.1 --deployment-files virt --network-protocol ipv4 --network-backend geneve,vlan --network-ovn true --storage-backend lvm

**Comment by asyedham** [comment]
PR #400 fixes this issue
