### ISSUE TITLE
Package installs are failing on Fedora 30 host

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/jetpack#43]
All the infrared dependencies installed by tasks/setup_infrared.yml are installed properly as seen here
```console
TASK [Install dependencies] **********************************************************************************************************************
ok: [localhost] => (item=git)
ok: [localhost] => (item=gcc)
ok: [localhost] => (item=libffi-devel)
ok: [localhost] => (item=python-virtualenv)
ok: [localhost] => (item=libselinux-python)
```
At the point where the playbook load_facts.yml playbook is running there is no inventory defined and localhost simply refers to implicit localhost which will use the right python module for dnf based on interpreter on the localhost which in my case is 3.7
```console
[smalleni@localhost jetpack]$ ansible --version
ansible 2.8.4
  config file = /home/smalleni/jetpack/ansible.cfg
  configured module search path = ['/home/smalleni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

```
However, when the setup_undercloud.yml playbook is running, I see failures as in
```console
 TASK [Install sshpass] ***************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "dnf install -y python2-dnf", "msg": "Could not import the dnf python module using /usr/bin/python (2.7.16 (default, Apr 30 2019, 15:54:43) [GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)]). Please install `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter.", "rc": 1, "results": [], "stderr": "Error: Unable to find a match\n", "stderr_lines": ["Error: Unable to find a match"], "stdout": "Last metadata expiration check: 0:14:13 ago on Tue 01 Oct 2019 09:09:12 PM EDT.\nNo match for argument: python2-dnf\n", "stdout_lines": ["Last metadata expiration check: 0:14:13 ago on Tue 01 Oct 2019 09:09:12 PM EDT.", "No match for argument: python2-dnf"]}
```

This seems to be because by this point we have localhost defined in an inventory file at /.infrared/.workspaces/workspace_2019-10-01_21-31-33/hosts which looks like
```
localhost ansible_connection=local  ansible_python_interpreter=python

[local]
localhost
```

At this point localhost is no longer implicit and the python interpreter used does not default to what is on the ansible controller (localhost).

For reference please see https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html and https://github.com/ansible/ansible/issues/54855

**Comment by smalleni** [comment]
@zulcss want to pick up this interesting one? One idea is to move all package installs before we generate inventory, but is there a better way?

**Comment by zulcss** [comment]
Wouldnt delegate_to: localhost work in this case?

**Comment by smalleni** [comment]
Can you try?

**Comment by smalleni** [comment]
On second thought, I don't think that would because when you delegate_to: localhost (after localhost exists in inventory file) it uses localhost from inventory not the implicit localhost.

**Comment by venkataanil** [comment]
> @zulcss want to pick up this interesting one? One idea is to move all package installs before we generate inventory, but is there a better way?

Did that here https://github.com/redhat-performance/jetpack/commit/8c22189286ef013c10be3db40484a7b11cda5eab
