### ISSUE TITLE
Change OSP 16 ML2/OVN deployments to DVR by default

### ISSUE THREAD

**Issue by sanjaychari** [redhat-performance/jetpack#438]
OSP 16/Train with ML2/OVN has DVR enabled by default.
https://github.com/openstack/tripleo-heat-templates/blob/stable/train/deployment/neutron/neutron-plugin-ml2-ovn.yaml#L183
Jetpack should also have this change.

**Comment by karelyatin** [comment]
Also found a similar issue[1] which is closed with reference to https://github.com/redhat-performance/jetpack/pull/167 but doesn't look that closes it. Also there was a question if extra_templates option in group_vars/all.yml to pass the DVR template can be used.

[1] https://github.com/redhat-performance/jetpack/issues/166
