### ISSUE TITLE
set boot_mode to bios at the time of undercloud install

### ISSUE THREAD

**Issue by kemmy22** [redhat-performance/jetpack#476]
At present the boot_mode is set per node basis and is added to node capabilities at the time of overcloud deployment or when the deployment is triggered through jetpack with tag overcloud.

With the default boot_mode being uefi starting OSP17, there can be scenarios where certain hosts do not enter PXE mode at the time of introspection due to the default boot mode being UEFI whereas the host itself is in bios mode.

This can't be handled specifically at the time of introspection because for triggering introspection the control is transferred to infrared and it returns back only after the introspection is complete.

While infrared does have an option of specifying boot-mode, it would require a code change in infrared to handle it since they have only mentioned a if clause to handle the scenario where boot-mode is uefi assuming the default to be bios, but that's not the case with OSP17.

**Comment by rajeshP524** [comment]
This issue was resolved with https://github.com/redhat-performance/jetpack/pull/477
