### ISSUE TITLE
[OSP17] Disable extending overcloud partitions for now

### ISSUE THREAD

**Issue by kemmy22** [redhat-performance/jetpack#495]
Customise overcloud partitions only when 'remote_image_path' is specified..a.k.a when we're using overcloud-full-uefi image.

**Comment by asyedham** [comment]
We no longer using custom overcloud images.

**Comment by kemmy22** [comment]
Yes, i saw your change for adding support for overcloud_full image. Hence, created this issue for making this optional because extending overcloud partitions won't work with overcloud_full image.

**Comment by asyedham** [comment]
Since jetpack now supports overcloud-full we can deprecate extending overcloud partitions instead of making it optional
