### ISSUE TITLE
RFE - Jetpack optimisation request for DVR or NON-DVR deployment

### ISSUE THREAD

**Issue by pradiptapks** [redhat-performance/jetpack#496]
The Jetpack environment template file (`group_var/all.yaml`) should be optimized with the below steps to standardize the Jetpack user environment file for DVR or NON-DVR-based deployment.

1. ` all.yaml ` should only provide the below conditional check for the user input.

    Example:- `DVREnabled: True` ##Default

2. Based on the above condition check Jetpack execute the respective ansible task in the backend with necessary changes in tripleo deployment templates.

In this way, I think the user environment file should be minimized. Please do add your thoughts for further optimization of the deployment

**Comment by sanjaychari** [comment]
@pradiptapks 

This sounds like a good idea. Right now, we do not have a flag for DVR in `group_vars/all.yml`, but once https://github.com/redhat-performance/jetpack/pull/461 is merged, the flag will be there and the changes in tripleo deployment templates can be moved to ansible tasks like you mentioned.
