### ISSUE TITLE
provision undercloud with RHEL 8

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#5]
OSP15 needs RHEL8 on undercloud. So this tool has to install RHEL8 on undercloud

**Comment by smalleni** [comment]
Something like this worked on supermicro systems
hammer -u cloud22 -p 123456 host update --name FQDN --build 1 --operatingsystem 'RHEL 8' --parameters overcloud=false --overwrite 1
 ipmitool -I lanplus -H mgmt-f05-h01-000-1029p.rdu2.scalelab.redhat.com -U quads -P 496280 chassis bootdev pxe options=persistent
 ipmitool -I lanplus -H mgmt-f05-h01-000-1029p.rdu2.scalelab.redhat.com -U quads -P 496280 chassis power cycle

**Comment by venkataanil** [comment]
Do you want to convert them into ansible tasks and push a PR?

**Comment by smalleni** [comment]
@venkataanil yes, will work on it today.

**Comment by smalleni** [comment]
@venkataanil I also need to test it with dells using badfish.
