### ISSUE TITLE
pass undercloud.conf to undercloud install command

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#51]
The default path which they are using is invalid for osp15 and osp16,

TASK [copy default undercloud config] ******************************************
^[[1;30mtask path: /home/kumar/.infrared/plugins/tripleo-undercloud/configure.yml:73^[[0m
^[[0;31mfatal: [f03-h05-000-r620.rdu2.scalelab.redhat.com]: FAILED! => {"changed": false, "msg": "Source /usr/share/python3-tripleoclient/undercloud.conf.sample not found"}^[[0m

I have seen in RDO spec as well and it is copied to /usr/share/python-tripleoclient/undercloud.conf.sample and not /usr/share/python3-tripleoclient/undercloud.conf.sample

As infrared team is not bothered about this, provide our own undercloud.conf instead of depending on infrared default undercloud.conf

**Comment by smalleni** [comment]
But for OSP 15 and 16 we install python3-tripleoclient right?

**Comment by venkataanil** [comment]
Yes, but it will be installed as python-tripleoclient as destination and conf path should be 
/usr/share/python-tripleoclient/undercloud.conf.sample

**Comment by venkataanil** [comment]
Commit 464c2980fc0567efdcd054fd985e15197a9a93ef fixed this issue.
