### ISSUE TITLE
Ignore any failures while cleaning network interfaces during undercloud setup stage

### ISSUE THREAD

**Issue by kemmy22** [redhat-performance/jetpack#510]
When we provision undercloud using a different image (other than foreman) and deploy using jetpack the deployment fails at prepare undercloud stage due to the absence of clean-interfaces.sh script to remove the existing network config in case of an image from foreman.
However, if we're using another image that config won't be there anyhow which leads to failure in deployment.

**Comment by sanjaychari** [comment]
+1 I have also faced this issue.
