### ISSUE TITLE
osp10 installation fails

### ISSUE THREAD

**Issue by zulcss** [redhat-performance/jetpack#52]
This is due to the fact that we are setting the gateway in the network-environment.yaml to 192.168.24.1 while the default in the undercloud is still 192.0.2.1.

**Comment by venkataanil** [comment]
Did u try changing https://github.com/redhat-performance/jetpack/blob/master/group_vars/all.yml#L42 ?

**Comment by zulcss** [comment]
Yes, I tried and got the following install error:

https://gist.github.com/zulcss/12d5bb5e00351431c0b0a170e36d3859

**Comment by zulcss** [comment]
With the workaround it works fine.
