### ISSUE TITLE
Use vlans numbers above 300 for network isolation

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#59]
Currently we use vlans 10, 20, 30, 40, 50 in network_environment [1] for network isolation for director deployment. Looks like some of these VLANs are used in Lab for public network

Change them to VLANs 300, 301, 302, 303, 304.
Also get these values along with allocation pools and cidr(InternalApiNetCidr) for user through group_vars.

[1] https://github.com/redhat-performance/jetpack/blob/master/files/virt/network/network-environment.yaml.j2

**Comment by asyedham** [comment]
Working on it
