### ISSUE TITLE
Issue all OS provisioning commands from jump host

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#61]
We are using hammer host to generate a build job in foreman which updates the host to provision with new OS on next boot.
https://github.com/redhat-performance/jetpack/blob/master/setup_undercloud.yml#L60-L89

The other tasks i.e
1) setting boot device to pxe
2) reboot the node

are doing from the ansible host. If we use hammer host for these tasks as well, then we can avoid installing packages needed for these tasks on the ansible host.

**Comment by smalleni** [comment]
Closed via c28766067d4bff3e1f3988a0eb54abdb417d68d2
