### ISSUE TITLE
log to jetpack folder

### ISSUE THREAD

**Issue by venkataanil** [redhat-performance/jetpack#69]
Currently infrared commands are logged inside home directory (i.e ~/infrared ).
1) https://github.com/redhat-performance/jetpack/blob/master/intropsect.yml#L11
2) https://github.com/redhat-performance/jetpack/blob/master/overcloud.yml#L63
3) https://github.com/redhat-performance/jetpack/blob/master/overcloud.yml#L71
4) https://github.com/redhat-performance/jetpack/blob/master/undercloud.yml#L10
5) https://github.com/redhat-performance/jetpack/blob/master/tag.yml#L16

We need to create "logs" directory inside jetpack directory and create these log files there.

**Comment by smalleni** [comment]
@asyedham update?

**Comment by asyedham** [comment]
@smalleni have raised the PR #71
