### ISSUE TITLE
Failure with osp10

### ISSUE THREAD

**Issue by zulcss** [redhat-performance/jetpack#70]
overcloud.Controller.0.ExternalPort.ExternalPort:
  resource_type: OS::Neutron::Port
  physical_resource_id: 
  status: CREATE_FAILED
  status_reason: |
    IpAddressGenerationFailureClient: resources.ExternalPort: No more IP addresses available on network be3a70aa-6e55-42f3-9a7e-613267fa78f5.
    Neutron server returns request_ids: ['req-ddb484d2-e3a7-42bf-a128-b1a24b310c68']

**Comment by smalleni** [comment]
What is the external network range in your network-environment.yaml

**Comment by zulcss** [comment]
https://github.com/redhat-performance/jetpack/pull/72
