### ISSUE TITLE
osp15: undercloud deployment fails with RHEL8

### ISSUE THREAD

**Issue by asyedham** [redhat-performance/jetpack#92]
TASK [run tripleo-undercloud] *****************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "source /root/infrared/.venv/bin/activate\ninfrared tripleo-undercloud -vv --version 15 --build passed_phase2 --images-task rpm --config-file /root/undercloud.conf &> undercloud_install.log\n", "delta": "0:09:50.331459", "end": "2019-10-30 13:14:43.667363", "msg": "non-zero return code", "rc": 2, "start": "2019-10-30 13:04:53.335904", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

undercloud_install.log

TASK [print any nested error entries in undercloud installation] ***************
^[[1;30mtask path: /root/.infrared/plugins/tripleo-undercloud/deploy.yml:41^[[0m
^[[0;33mchanged: [undercloud] => {"changed": true, "cmd": "grep -B2 -A5 -i 'info:.*error:' undercloud_install.log || true", "delta": "0:00:00.003589", "end": "2019-10-30 13:14:43.427034", "rc": 0, "start": "2019-10-30 13:14:43.423445", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}^[[0m

TASK [fail] ********************************************************************
^[[1;30mtask path: /root/.infrared/plugins/tripleo-undercloud/deploy.yml:44^[[0m
^[[0;31mfatal: [undercloud]: FAILED! => {"changed": false, "msg": "Undercloud deployment failed... :("}^[[0m

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/root/.infrared/plugins/tripleo-undercloud/main.retry

PLAY RECAP *********************************************************************
^[[0;33mlocalhost^[[0m                  : ^[[0;32mok=8   ^[[0m ^[[0;33mchanged=4   ^[[0m unreachable=0    failed=0
^[[0;31mundercloud^[[0m                 : ^[[0;32mok=104 ^[[0m ^[[0;33mchanged=64  ^[[0m unreachable=0    ^[[0;31mfailed=1   ^[[0m

^[[31mERROR   Playbook "/root/.infrared/plugins/tripleo-undercloud/main.yml" failed!^[[0m

**Comment by smalleni** [comment]
@asyedham What was the issue and why has this been closed? Please comment saying this was not an issue if that was the case. Thanks.

**Comment by asyedham** [comment]
@smalleni Deployed undercloud on osp15 successfully after the latest changes where merged. So have closed this issue
